spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hiber
    driver-class-name: org.postgresql.Driver
    username: sharkvale
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
server:
  servlet:
    context-path: /
